name: Spec PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-and-upload-yaml-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create YAML File
        run: |
          echo 'wget https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml' > tests/openapi-bundled.yaml

      - name: Upload YAML Artifact
        uses: actions/upload-artifact@v2
        with:
          name: openapi-bundled
          path: tests/openapi-bundled.yaml
